name: Build C++

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
      - uses: actions/checkout@v3
        run: |
          sudo apt-get update
          sudo apt-get install -y -f build-essential g++ cmake
          g++ main.cpp -std=c++17 -Wall -Wextra -Werror -o main_program
